name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      image-5640: ${{ steps.filter.outputs.image-5640 }}
      image-746: ${{ steps.filter.outputs.image-746 }}
      image-747: ${{ steps.filter.outputs.image-747 }}
      image-7410: ${{ steps.filter.outputs.image-7410 }}
      image-800-beta1: ${{ steps.filter.outputs.image-800-beta1 }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            image-5640:
              - './php-fpm/5.6.40/**'
            image-746:
              - './php-fpm/7.4.6/**'
            image-747:
              - './php-fpm/7.4.7/**'
            image-7410:
              - './php-fpm/7.4.10/**'
            image-800-beta1:
              - './php-fpm/8.0.0-beta1/**'

  build-php-5640:
    needs: changes
    if: ${{ needs.changes.outputs.image-5640 == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/5.6.40/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:5.6.40

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-746:
    needs: changes
    if: ${{ needs.changes.outputs.image-746 == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.6/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.6

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-747:
    needs: changes
    if: ${{ needs.changes.outputs.image-747 == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.7/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.7

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-7410:
    needs: changes
    if: ${{ needs.changes.outputs.image-7410 == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.10/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.10

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-800-beta1:
    needs: changes
    if: ${{ needs.changes.outputs.image-800-beta1 == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/8.0.0-beta1/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:8.0.0-beta1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
