name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-php-5640:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/5.6.40/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:5.6.40

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-746:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.6/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.6

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-747:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.7/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.7

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-7410:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/7.4.10/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:7.4.10

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-php-800-beta1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./php-fpm/8.0.0-beta1/Dockerfile
          push: true
          tags: diazdavid/test-integration-dockerhub:8.0.0-beta1

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
